name: lyrically_spotify_like
description: Spotify-like player with Admin/Advertiser/User flows using Firebase REST + just_audio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI + state + HTTP + audio
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  shared_preferences: ^2.3.2

  # Optional (for push notifications later; safe to leave)
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/data/songs.json
